//===- Physical.td -----------------------------------------*- tablegen -*-===//
//
// This file is licensed under the MIT License.
// SPDX-License-Identifier: MIT
//
// Copyright (C) 2022, Advanced Micro Devices, Inc.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_PHY_DIALECT_PHYSICAL_TD
#define MLIR_PHY_DIALECT_PHYSICAL_TD

include "phy/Dialect/Physical/PhysicalTypes.td"
include "phy/Dialect/Physical/PhysicalOps.td"

#endif  // MLIR_PHY_DIALECT_PHYSICAL_TD
