//===- PhyPasses.td ----------------------------------------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef PHY_PASSES_
#define PHY_PASSES_

include "mlir/Pass/PassBase.td"

#endif  // PHY_PASSES_
