//===- PhyTypes.td -----------------------------------------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_DIALECT_PHY_TYPES_TD
#define MLIR_DIALECT_PHY_TYPES_TD


#endif  // MLIR_DIALECT_PHY_TYPES_TD
