//===- Layout.td -------------------------------------------*- tablegen -*-===//
//
// This file is licensed under the MIT License.
// SPDX-License-Identifier: MIT
//
// Copyright (C) 2022, Advanced Micro Devices, Inc.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_PHY_DIALECT_LAYOUT_TD
#define MLIR_PHY_DIALECT_LAYOUT_TD

include "phy/Dialect/Layout/LayoutOps.td"

#endif  // MLIR_PHY_DIALECT_LAYOUT_TD
