//===- SpatialPasses.td ------------------------------------*- tablegen -*-===//
//
// This file is licensed under the MIT License.
// SPDX-License-Identifier: MIT
//
// Copyright (C) 2022, Advanced Micro Devices, Inc.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_PHY_DIALECT_SPATIAL_PASSES_TD
#define MLIR_PHY_DIALECT_SPATIAL_PASSES_TD

include "phy/Dialect/Spatial/SpatialBase.td"

include "mlir/Pass/PassBase.td"

#endif  // MLIR_PHY_DIALECT_SPATIAL_PASSES_TD
