##===- build-and-test.yml - GitHub CI --------------------------*- yaml -*-===//
##
## This file builds and tests MLIR-PHY on every push and PR.
##
## This file is licensed under the MIT License.
## See https://llvm.org/LICENSE.txt for license information.
## SPDX-License-Identifier: MIT
##
## Copyright (C) 2022, Advanced Micro Devices, Inc.
##
##===----------------------------------------------------------------------===//

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.build }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build: ["Debug", "Release"]
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - name: Checkout myself
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          ./.github/scripts/install-build-deps.sh

      - name: Configure myself
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            -DLLVM_EXTERNAL_LIT=`which lit` \
            -DCMAKE_MAKE_PROGRAM=ninja \
            -G Ninja

      - name: Build myself
        run: cmake --build build --target all

      - name: Test myself
        run: cmake --build build --target check-phy
