##===- generate-docs.yml - GitHub CI ---------------------------*- yaml -*-===//
##
## This file generates the documentation on every push to main.
##
## This file is licensed under the MIT License.
## SPDX-License-Identifier: MIT
##
## Copyright (C) 2022, Advanced Micro Devices, Inc.
##
##===----------------------------------------------------------------------===//

name: Generate Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Generate Documentation
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout myself
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          ./.github/scripts/install-build-deps.sh

      - name: Configure myself
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_EXTERNAL_LIT=`which lit` \
            -DCMAKE_MAKE_PROGRAM=ninja \
            -G Ninja

      - name: Build documentation
        run: |
          cmake --build build --target phy-doc
          cp README.md ./build/docs/

      - name: Publish to github-pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
          enable_jekyll: true
